/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logined.QuanLyGianHang;

import javax.swing.JLayeredPane;

/**
 *
 * @author Admin
 */
public class SuaHang extends javax.swing.JPanel {

    /**
     * Creates new form SuaHang
     */
    public SuaHang(int page) {
        initComponents();
        this.page = page;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbDonVi = new javax.swing.JComboBox<>();
        cmbPhanLoai = new javax.swing.JComboBox<>();
        txtGiaGoc = new javax.swing.JTextField();
        txtKhuyenMai = new javax.swing.JTextField();
        txtViTri = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnNhapLai = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel3.setText("Quản Lý Gian Hàng/ Sửa Hàng");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Mã SP:");
        jLabel9.setEnabled(false);
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txtMaSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaSP.setEnabled(false);
        add(txtMaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, -1));

        txtTenSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 480, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên Sản Phẩm:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Đơn Vị:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        cmbDonVi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(cmbDonVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 230, -1));

        cmbPhanLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(cmbPhanLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 230, -1));

        txtGiaGoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtGiaGoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 140, -1));

        txtKhuyenMai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 100, -1));

        txtViTri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtViTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 140, -1));

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 140, -1));

        btnSua.setBackground(new java.awt.Color(13, 138, 254));
        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setToolTipText("");
        btnSua.setPreferredSize(new java.awt.Dimension(80, 28));
        add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        btnNhapLai.setBackground(new java.awt.Color(13, 138, 254));
        btnNhapLai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.setToolTipText("");
        btnNhapLai.setPreferredSize(new java.awt.Dimension(80, 28));
        add(btnNhapLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Số Lượng:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Vị Trí:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Khuyến Mãi (%):");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Giá Gốc:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Phân Loại:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("VND");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("%");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        btnBack.setBackground(new java.awt.Color(234, 107, 72));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("< Back");
        btnBack.setToolTipText("");
        btnBack.setPreferredSize(new java.awt.Dimension(80, 28));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ((JLayeredPane)this.getParent()).add(new Home(page), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));
        this.setVisible(false);
        ((JLayeredPane)this.getParent()).remove(this);
    }//GEN-LAST:event_btnBackActionPerformed

    private int page;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JComboBox<String> cmbDonVi;
    private javax.swing.JComboBox<String> cmbPhanLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtGiaGoc;
    private javax.swing.JTextField txtKhuyenMai;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables
}
