/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logined;

import Logined.QuanLyGianHang.PaneQuanLyGianHang;
import Logined.QuanLyKhoHang.PaneQuanLyKhoHang;
import Logined.QuanLyNhanVien.PaneQuanLyNhanVien;
import Logined.QuanLyTaiKhoan.PaneQuanLyTaiKhoan;
import MainPackage.MainFrame;
import java.awt.Frame;

/**
 *
 * @author Admin
 */
public class LoginedPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginedPanel
     */
    public LoginedPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Layer = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblQuyenThucHien = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnQuanLyTaiKhoan = new javax.swing.JButton();
        btnQuanLyGianHang = new javax.swing.JButton();
        btnQuanLyKhoHang = new javax.swing.JButton();
        btnQuanLyNhanVien = new javax.swing.JButton();

        setBackground(new java.awt.Color(38, 58, 83));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Layer.setBackground(new java.awt.Color(255, 255, 255));
        Layer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Layer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(Layer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 760, 770));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Xin Chào,");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblTenDangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTenDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblTenDangNhap.setText("Adminstrator");
        add(lblTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quyền:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblQuyenThucHien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuyenThucHien.setForeground(new java.awt.Color(255, 255, 255));
        lblQuyenThucHien.setText("Admin");
        add(lblQuyenThucHien, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        lblDangXuat.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        lblDangXuat.setText("Đăng Xuất");
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
        });
        add(lblDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo.png"))); // NOI18N
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 165));

        btnQuanLyTaiKhoan.setBackground(new java.awt.Color(38, 58, 83));
        btnQuanLyTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnQuanLyTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TaiKhoanIcon.png"))); // NOI18N
        btnQuanLyTaiKhoan.setText("Quản Lý Tài Khoản");
        btnQuanLyTaiKhoan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnQuanLyTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyTaiKhoan.setMargin(new java.awt.Insets(0, 50, 0, 0));
        btnQuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyTaiKhoanActionPerformed(evt);
            }
        });
        add(btnQuanLyTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 269, 54));

        btnQuanLyGianHang.setBackground(new java.awt.Color(38, 58, 83));
        btnQuanLyGianHang.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnQuanLyGianHang.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyGianHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/GianHangIcon.png"))); // NOI18N
        btnQuanLyGianHang.setText("Quản Lý Gian Hàng");
        btnQuanLyGianHang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnQuanLyGianHang.setDefaultCapable(false);
        btnQuanLyGianHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyGianHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyGianHang.setMargin(new java.awt.Insets(0, 50, 0, 0));
        btnQuanLyGianHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyGianHangActionPerformed(evt);
            }
        });
        add(btnQuanLyGianHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 269, 54));

        btnQuanLyKhoHang.setBackground(new java.awt.Color(38, 58, 83));
        btnQuanLyKhoHang.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnQuanLyKhoHang.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyKhoHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KhoHangIcon.png"))); // NOI18N
        btnQuanLyKhoHang.setText("Quản Lý Kho Hàng");
        btnQuanLyKhoHang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnQuanLyKhoHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyKhoHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyKhoHang.setMargin(new java.awt.Insets(0, 50, 0, 0));
        btnQuanLyKhoHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyKhoHangActionPerformed(evt);
            }
        });
        add(btnQuanLyKhoHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 269, 54));

        btnQuanLyNhanVien.setBackground(new java.awt.Color(38, 58, 83));
        btnQuanLyNhanVien.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnQuanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/NhanVienIcon.png"))); // NOI18N
        btnQuanLyNhanVien.setText("Quản Lý Nhân Viên");
        btnQuanLyNhanVien.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnQuanLyNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyNhanVien.setMargin(new java.awt.Insets(0, 50, 0, 0));
        btnQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhanVienActionPerformed(evt);
            }
        });
        add(btnQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 269, 54));
    }// </editor-fold>//GEN-END:initComponents

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        // TODO add your handling code here:
        MainFrame newApp = new MainFrame();
        newApp.setVisible(true);
        newApp.setLocationRelativeTo(null);
        ((Frame)this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void btnQuanLyGianHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyGianHangActionPerformed
        // TODO add your handling code here:
        Layer.removeAll();
        Layer.add(new PaneQuanLyGianHang(), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 770));
        Layer.repaint();
        Layer.revalidate();
    }//GEN-LAST:event_btnQuanLyGianHangActionPerformed

    private void btnQuanLyKhoHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyKhoHangActionPerformed
        // TODO add your handling code here:
        Layer.removeAll();
        Layer.add(new PaneQuanLyKhoHang(), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 770));
        Layer.repaint();
        Layer.revalidate();
    }//GEN-LAST:event_btnQuanLyKhoHangActionPerformed

    private void btnQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNhanVienActionPerformed
        // TODO add your handling code here:
        Layer.removeAll();
        Layer.add(new PaneQuanLyNhanVien(), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 770));
        Layer.repaint();
        Layer.revalidate();
    }//GEN-LAST:event_btnQuanLyNhanVienActionPerformed

    private void btnQuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyTaiKhoanActionPerformed
        // TODO add your handling code here:
        Layer.removeAll();
        Layer.add(new PaneQuanLyTaiKhoan(), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 770));
        Layer.repaint();
        Layer.revalidate();
    }//GEN-LAST:event_btnQuanLyTaiKhoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Layer;
    private javax.swing.JButton btnQuanLyGianHang;
    private javax.swing.JButton btnQuanLyKhoHang;
    private javax.swing.JButton btnQuanLyNhanVien;
    private javax.swing.JButton btnQuanLyTaiKhoan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblQuyenThucHien;
    private javax.swing.JLabel lblTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
