/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logined.QuanLyKhoHang;

/**
 *
 * @author Admin
 */
public class PaneQuanLyKhoHang extends javax.swing.JPanel {

    /**
     * Creates new form PaneQuanLyKhoHang
     */
    public PaneQuanLyKhoHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Layer = new javax.swing.JLayeredPane();
        homeQuanLyKhoHang2 = new Logined.QuanLyKhoHang.HomeQuanLyKhoHang();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Layer.setAlignmentX(0.0F);
        Layer.setAlignmentY(0.0F);
        Layer.setMinimumSize(new java.awt.Dimension(760, 770));
        Layer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Layer.add(homeQuanLyKhoHang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(Layer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 770));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Layer;
    private Logined.QuanLyKhoHang.HomeQuanLyKhoHang homeQuanLyKhoHang2;
    // End of variables declaration//GEN-END:variables
}
