package MainPackage;


import Logined.LoginedPanel;
import java.awt.Color;
import java.awt.Component;
import javax.swing.AbstractButton;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import sun.swing.table.DefaultTableCellHeaderRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        PaneDangNhap.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Layer = new javax.swing.JLayeredPane();
        NotLoginPanel = new javax.swing.JPanel();
        PaneDangNhap = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnXemKhuyenMai = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachSanPham = new javax.swing.JTable();
        btnPrev = new javax.swing.JButton();
        lblTrangHienTai = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnHienThiPaneDangNhap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbKetQua = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbTongSanPham = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản Lý Siêu Thị");

        Layer.setPreferredSize(new java.awt.Dimension(1024, 768));
        Layer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NotLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        NotLoginPanel.setForeground(new java.awt.Color(255, 255, 255));
        NotLoginPanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        NotLoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaneDangNhap.setBackground(new java.awt.Color(58, 161, 207));
        PaneDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        PaneDangNhap.setPreferredSize(new java.awt.Dimension(450, 217));
        PaneDangNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Đăng Nhập sử dụng tài khoản ACC SPM");
        PaneDangNhap.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("User");
        PaneDangNhap.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        PaneDangNhap.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btnDangNhap.setBackground(new java.awt.Color(38, 58, 88));
        btnDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.setPreferredSize(new java.awt.Dimension(140, 30));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        PaneDangNhap.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btnHuy.setBackground(new java.awt.Color(234, 107, 72));
        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.setPreferredSize(new java.awt.Dimension(140, 30));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        PaneDangNhap.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PaneDangNhap.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 380, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PaneDangNhap.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 380, -1));

        NotLoginPanel.add(PaneDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 338, 455, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NotLoginPanel.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 630, -1));

        btnTim.setBackground(new java.awt.Color(13, 138, 254));
        btnTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setText("Tìm");
        btnTim.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTim.setPreferredSize(new java.awt.Dimension(75, 25));
        NotLoginPanel.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        btnXemKhuyenMai.setBackground(new java.awt.Color(13, 138, 254));
        btnXemKhuyenMai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXemKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        btnXemKhuyenMai.setText("Xem Khuyến Mãi");
        btnXemKhuyenMai.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnXemKhuyenMai.setPreferredSize(new java.awt.Dimension(133, 25));
        NotLoginPanel.add(btnXemKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, -1, -1));

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/RoofSPM_BUTTON.png"))); // NOI18N
        btnRefresh.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnRefresh.setPreferredSize(new java.awt.Dimension(1024, 215));
        NotLoginPanel.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1024, 450));

        tblDanhSachSanPham.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDanhSachSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDanhSachSanPham.setForeground(new java.awt.Color(255, 255, 255));
        tblDanhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSachSanPham.setFocusable(false);
        tblDanhSachSanPham.setRowHeight(25);
        tblDanhSachSanPham.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDanhSachSanPham);

        NotLoginPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        btnPrev.setBackground(new java.awt.Color(13, 138, 254));
        btnPrev.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("Prev");
        btnPrev.setBorder(null);
        btnPrev.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPrev.setPreferredSize(new java.awt.Dimension(80, 25));
        NotLoginPanel.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 678, -1, -1));

        lblTrangHienTai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTrangHienTai.setText("Trang 0");
        NotLoginPanel.add(lblTrangHienTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 683, -1, -1));

        btnNext.setBackground(new java.awt.Color(13, 138, 254));
        btnNext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next");
        btnNext.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnNext.setPreferredSize(new java.awt.Dimension(80, 25));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        NotLoginPanel.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 678, -1, -1));

        btnHienThiPaneDangNhap.setBackground(new java.awt.Color(13, 138, 254));
        btnHienThiPaneDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHienThiPaneDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnHienThiPaneDangNhap.setText("Đăng Nhập");
        btnHienThiPaneDangNhap.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnHienThiPaneDangNhap.setPreferredSize(new java.awt.Dimension(160, 35));
        btnHienThiPaneDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiPaneDangNhapActionPerformed(evt);
            }
        });
        NotLoginPanel.add(btnHienThiPaneDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 721, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Hiển thị kết quả từ");
        NotLoginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, -1, -1));

        lbKetQua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbKetQua.setText("1-20");
        NotLoginPanel.add(lbKetQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 710, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("trong tổng số");
        NotLoginPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 710, -1, -1));

        lbTongSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTongSanPham.setText("4321");
        NotLoginPanel.add(lbTongSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 710, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("sản phẩm.");
        NotLoginPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 710, -1, -1));

        Layer.add(NotLoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1034, 801));

        getContentPane().add(Layer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHienThiPaneDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiPaneDangNhapActionPerformed
        // TODO add your handling code here:
        PaneDangNhap.setVisible(true);
        tblDanhSachSanPham.setEnabled(false);
        btnRefresh.setEnabled(false);
        btnPrev.setEnabled(false);
        btnNext.setEnabled(false);
        btnTim.setEnabled(false);
        btnXemKhuyenMai.setEnabled(false);
        txtSearch.setEnabled(false);
        btnHienThiPaneDangNhap.setEnabled(false);
    }//GEN-LAST:event_btnHienThiPaneDangNhapActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        PaneDangNhap.setVisible(false);
        tblDanhSachSanPham.setEnabled(true);
        btnRefresh.setEnabled(true);
        btnPrev.setEnabled(true);
        btnNext.setEnabled(true);
        btnTim.setEnabled(true);
        btnXemKhuyenMai.setEnabled(true);
        txtSearch.setEnabled(true);
        btnHienThiPaneDangNhap.setEnabled(true);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        Layer.remove(NotLoginPanel);
        Layer.add(new LoginedPanel(), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
        Layer.repaint();
        Layer.revalidate();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame jframe = new MainFrame();
                jframe.setVisible(true);
                jframe.setLocationRelativeTo(null);
                
                //new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Layer;
    private javax.swing.JPanel NotLoginPanel;
    private javax.swing.JPanel PaneDangNhap;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnHienThiPaneDangNhap;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXemKhuyenMai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbKetQua;
    private javax.swing.JLabel lbTongSanPham;
    private javax.swing.JLabel lblTrangHienTai;
    private javax.swing.JTable tblDanhSachSanPham;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
